### PR TITLE
Fix missing import for external []byte alias

### LINKED ISSUE #166: External reference to `[]byte` type does not import package in generated code
With an externa package like:
```
type External []byte
```

and the target ssz package like:
```
import "GitHub.com..../external"

type X struct {
   A external.External
}
```
The generated code creates the encodings but does not import "gitHub.com.../external".

### PR DESCRIPTION
**Pull request by ferranbt**
Closes #166

### CODE REVIEW

File: sszgen/generator/unmarshal.go [hunk 1]
```diff
@@ -39,22 +39,18 @@ func (v *Value) unmarshal(dst string) string {
...
 
-		refName := ""
-		if v.ref != "" {
-			refName = v.ref + "." + v.obj
-		}
-
 		// both fixed and dynamic are decoded equally
 		tmpl := `{{.validate}}if cap(::.{{.name}}) == 0 {
-			{{if .refName}} ::.{{.name}} = {{ .refName }}(make([]byte, 0, len({{.dst}}))) {{ else }} ::.{{.name}} = make([]byte, 0, len({{.dst}})) {{ end }}
+			{{if .isRef}} ::.{{.name}} = {{ ref .obj }}(make([]byte, 0, len({{.dst}}))) {{ else }} ::.{{.name}} = make([]byte, 0, len({{.dst}})) {{ end }}
```
Comment (ferranbt) [inline sszgen/generator/unmarshal.go:44]: The issue was here, you have to use the new `ref` function during the template to record the values that need to be imported.
